K8S_REPLICAS: '2'
K8S_MAX_UNAVAIL: '1'
K8S_MAX_SURGE: '1'
K8S_REQ_MEM: '64Mi'
K8S_REQ_CPU: '100m'
K8S_LIMIT_MEM: '128Mi'
K8S_LIMIT_CPU: '150m'
AUTOSCALE_MIN_REPLICA: '2'
AUTOSCALE_MAX_REPLICA: '4'
AUTOSCALE_CPU_PERCENTAGE: '50'