NAMESPACE: 'default'
K8S_REPLICAS: '2'
K8S_MAX_UNAVAIL: '1'
K8S_MAX_SURGE: '1'
K8S_REQ_MEM: '64Mi'
K8S_REQ_CPU: '100m'
K8S_LIMIT_MEM: '128Mi'
K8S_LIMIT_CPU: '150m'
AUTOSCALE_MIN_REPLICA: '2'
AUTOSCALE_MAX_REPLICA: '4'
AUTOSCALE_CPU_PERCENTAGE: '50'
DOCKER_APP_IMAGE: shubhamdevops2/crud:1.0.1-2022-09-12-15-49-12-main
mountPathForPVC: "/var/www/html"
label_for_node: 'frontend'
services:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007
    