NAMESPACE: 'default'
K8S_REPLICAS: '2'
K8S_MAX_UNAVAIL: '1'
K8S_MAX_SURGE: '1'
K8S_REQ_MEM: '64Mi'
K8S_REQ_CPU: '100m'
K8S_LIMIT_MEM: '128Mi'
K8S_LIMIT_CPU: '150m'
AUTOSCALE_MIN_REPLICA: '2'
AUTOSCALE_MAX_REPLICA: '4'
AUTOSCALE_CPU_PERCENTAGE: '50'
DOCKER_APP_IMAGE: shubham1769/myapp:0.0.24-2022-08-23-23-57-15-main