apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  type: "{{ .Values.services.type }}"
  ports:
  - port: "{{ .Values.services.ports.port }}"
    targetPort: "{{ .Values.services.ports.targetPort }}"
    nodePort: "{{ .Values.services.ports.nodePort }}"
    # protocol: TCP
    #name: https
  selector:
    app: "{{ .Values.label_for_node }}"